ChickenStock-2024/BackEnd

- src/main/java/com/sascom/chickenstock/global/error/GlobalExceptionHandler.java
- src/main/java/com/sascom/chickenstock/global/error/code/AuthErrorCode.java
- src/main/java/com/sascom/chickenstock/global/error/code/ChickenStockErrorCode.java
- src/main/java/com/sascom/chickenstock/global/error/code/GlobalErrorCode.java
- src/main/java/com/sascom/chickenstock/global/error/dto/ErrorResponse.java
- src/main/java/com/sascom/chickenstock/global/error/exception/AuthException.java
- src/main/java/com/sascom/chickenstock/global/error/exception/ChickenStockException.java
개발하며 예외처리를 위해 기본(global) 예외처리 추가
어떤 변경 사항이 있나요?
> [#2] 기본 예외처리 추가

- src/main/java/com/sascom/chickenstock/domain/rival/controller/RivalController.java
- src/main/java/com/sascom/chickenstock/domain/rival/dto/request/RequestEnrollRivalDTO.java
- src/main/java/com/sascom/chickenstock/domain/rival/dto/response/ResponseCheckRivalDTO.java
- src/main/java/com/sascom/chickenstock/domain/rival/dto/response/ResponseEnrollRivalDTO.java
- src/main/java/com/sascom/chickenstock/domain/rival/repository/RivalRepository.java
- src/main/java/com/sascom/chickenstock/domain/rival/service/RivalService.java
> [#1] Rival CRUD 구현

- src/main/java/com/sascom/chickenstock/domain/company/entity/Company.java
[#6 ] 이슈 제목
어떤 변경 사항이 있나요?
!테스트 사진 첨부!
> [#6] Company테이블에 code필드 추가

- src/main/java/com/sascom/chickenstock/domain/history/repository/HistoryRepository.java
- src/main/java/com/sascom/chickenstock/domain/history/service/HistoryService.java
feat [#12 ] History Create 구현
History Create 구현
어떤 변경 사항이 있나요?
!테스트 사진 첨부!
> [Feat] #12 - History Create 구현

- src/main/java/com/sascom/chickenstock/domain/account/controller/AccountController.java
- src/main/java/com/sascom/chickenstock/domain/account/dto/request/AccountCreateRequest.java
- src/main/java/com/sascom/chickenstock/domain/account/entity/Account.java
- src/main/java/com/sascom/chickenstock/domain/account/repository/AccountRepository.java
- src/main/java/com/sascom/chickenstock/domain/account/service/AccountService.java
- src/main/java/com/sascom/chickenstock/domain/history/repository/HistoryRepository.java
- src/main/java/com/sascom/chickenstock/domain/history/service/HistoryService.java
close [#14 ] Account Create 구현
Account Create 구현
어떤 변경 사항이 있나요?
> [#14 ] Account Create 구현

- src/main/java/com/sascom/chickenstock/domain/account/controller/AccountController.java
- src/main/java/com/sascom/chickenstock/domain/account/service/AccountService.java
- src/main/java/com/sascom/chickenstock/domain/competition/controller/CompetitionController.java
- src/main/java/com/sascom/chickenstock/domain/member/service/MemberService.java
[#18] 컴파일 오류 수정
main 브랜치의 컴파일 오류 수정.
- Optional 반환값에 대한 임시 예외처리
- import 작성
- 파라미터 타입 불일치 해결
어떤 변경 사항이 있나요?
> [#18] 컴파일 오류 수정

- src/main/java/com/sascom/chickenstock/domain/ranking/controller/RankingController.java
- src/main/java/com/sascom/chickenstock/domain/ranking/error/RankingExceptionHandler.java
- src/main/java/com/sascom/chickenstock/domain/ranking/error/code/RankingErrorCode.java
- src/main/java/com/sascom/chickenstock/domain/ranking/error/exception/RankingException.java
close #31 
기존에 작성한 RankingController의 Exception을 우리 서비스에 맞는 Exception으로 수했습니다.
어떤 변경 사항이 있나요?
> [#31] ranking 관련 error 추가

- src/main/java/com/sascom/chickenstock/domain/account/controller/AccountController.java
- src/main/java/com/sascom/chickenstock/domain/account/dto/response/ExecutionContentResponse.java
- src/main/java/com/sascom/chickenstock/domain/account/dto/response/HistoryInfo.java
- src/main/java/com/sascom/chickenstock/domain/account/dto/response/StockInfo.java
- src/main/java/com/sascom/chickenstock/domain/account/service/AccountService.java
- src/main/java/com/sascom/chickenstock/domain/account/service/RedisService.java
- src/main/java/com/sascom/chickenstock/domain/history/repository/HistoryRepository.java
- src/main/java/com/sascom/chickenstock/global/entity/BaseTimeEntity.java
- src/test/java/com/sascom/chickenstock/domain/account/repository/GetExcutionContentRepositoryTest.java
> [#27] - Account 체결 내역 조회 기능 개발 및 테스트 코드 작성

- src/main/java/com/sascom/chickenstock/domain/account/dto/request/StockOrderRequest.java
- src/main/java/com/sascom/chickenstock/domain/account/service/AccountService.java
- src/main/java/com/sascom/chickenstock/domain/trade/dto/ProcessedOrderDto.java
- src/main/java/com/sascom/chickenstock/domain/trade/service/TradeService.java
- src/main/java/com/sascom/chickenstock/domain/trade/util/ChickenStockManager.java
resolve #47
main에 급하게 merge해야 할 일이 있어서 작업 도중 merge를 했는데, main branch를 pull받고 실행하면 실행이 안되게 되어버렸습니다. 그래서 최소한으로 실행이 되도록 수정했습니다.
어떤 변경 사항이 있나요?
> [#47] - 실행 안되는 오류 수정

- src/main/java/com/sascom/chickenstock/domain/account/repository/AccountRepository.java
- src/main/java/com/sascom/chickenstock/domain/account/service/AccountService.java
- src/main/java/com/sascom/chickenstock/domain/auth/controller/AuthController.java
- src/main/java/com/sascom/chickenstock/domain/auth/dto/response/AccountInfoForLogin.java
- src/main/java/com/sascom/chickenstock/domain/auth/dto/response/ResponseLoginMember.java
- src/main/java/com/sascom/chickenstock/domain/competition/repository/CompetitionRepository.java
- src/main/java/com/sascom/chickenstock/domain/ranking/util/RatingCalculatorV1.java
- src/test/java/com/sascom/chickenstock/domain/auth/AuthControllerTest.java
resolve #62 email 로그인 시 response 수정
어떤 변경 사항이 있나요?
> #62 - email 로그인 시 response 수정

- src/main/java/com/sascom/chickenstock/domain/account/service/AccountService.java
- src/main/java/com/sascom/chickenstock/domain/competition/controller/CompetitionController.java
- src/main/java/com/sascom/chickenstock/domain/competition/dto/response/ActiveCompetitionResponse.java
- src/main/java/com/sascom/chickenstock/domain/competition/repository/CompetitionRepository.java
- src/main/java/com/sascom/chickenstock/domain/competition/service/CompetitionService.java
- resolve: #82 
- 가장 최근 대회의 상태 조회 구현
- 활성화된 대회 확인 메서드 추가 후 accountService에 사용
어떤 변경 사항이 있나요?
!테스트 사진 첨부!
> [#82] 대회 조회 구현

- src/main/java/com/sascom/chickenstock/domain/auth/dto/response/ResponseLoginMember.java
- resolve: #84 
알림 수신에 대한 정보를 추가했습니다.
어떤 변경 사항이 있나요?
> [#84] - 로그인 시 알림 수신여부 정보 추가

- src/main/java/com/sascom/chickenstock/domain/auth/controller/AuthController.java
- src/main/java/com/sascom/chickenstock/domain/auth/service/AuthService.java
- src/main/java/com/sascom/chickenstock/global/filter/JwtAuthenticationFilter.java
resolve #77 
로그아웃 기능 구현
로그아웃 요청 시 헤더로 들어온 Access Token을 통해 Redis에 있는 Refresh Token 삭제
블랙리스트 - Access Token을 key, "logout" value로 Redis에 다시 저장
이제 해당 Access Token이 블랙리스트라면 Filter에서 setAuthentication 안해줌
어떤 변경 사항이 있나요?
> [#77] 로그아웃 기능 구현

- src/main/java/com/sascom/chickenstock/domain/member/service/MemberFacade.java
- src/main/resources/application.yml
cookie 설정에서 path를 지정해주지 않아 새로 고침 시에 쿠키가 사라지는 현상이 있었습니다. 이 부분을 수정하였습니다.
어떤 변경 사항이 있나요?
> [#93] cookie 설정 수정

- src/main/java/com/sascom/chickenstock/domain/auth/dto/request/RequestSignupMember.java
- src/main/java/com/sascom/chickenstock/domain/auth/dto/response/ResponseLoginMember.java
- src/main/java/com/sascom/chickenstock/domain/auth/service/AuthService.java
- src/main/java/com/sascom/chickenstock/domain/member/dto/MemberInfoForLogin.java
- src/main/java/com/sascom/chickenstock/domain/member/entity/Member.java
- src/test/java/com/sascom/chickenstock/domain/auth/AuthControllerTest.java
resolve #98 
명세와 맞지 않은 대소문자와 snake case로 작성된 변수들을 수정했습니다.
어떤 변경 사항이 있나요?
> [#98] 대소문자, snake case 수정

- src/main/java/com/sascom/chickenstock/domain/member/service/MemberService.java
resolve #96 
비밀번호 변경 요청 시 검증 로직이 잘못된 것을 확인하여 급하게 수정하였습니다.
어떤 변경 사항이 있나요?
> [#96] 비밀번호 변경 시 검증 로직 수정

- src/main/java/com/sascom/chickenstock/domain/auth/service/AuthService.java
- src/main/java/com/sascom/chickenstock/domain/auth/service/ChickenstockOauth2MemberService.java
- src/main/java/com/sascom/chickenstock/domain/member/repository/MemberRepository.java
- src/main/java/com/sascom/chickenstock/domain/ranking/dto/CompetitionResultDto.java
- src/main/java/com/sascom/chickenstock/domain/ranking/dto/MemberRankingDto.java
- src/main/java/com/sascom/chickenstock/domain/ranking/dto/response/RankingListResponse.java
- src/main/java/com/sascom/chickenstock/domain/ranking/service/RankingService.java
resolve #91 
front에서 페이지 번호를 계산하기 위해 총 인원수를 보내줘야 할 필요성이 있어 수정하였습니다.
어떤 변경 사항이 있나요?
!테스트 사진 첨부!
> [#91] ranking 조회 response 수정

- src/main/resources/application.yml
- resolve: #108 
properties 수정
어떤 변경 사항이 있나요?
> [#108] sql, jpa properties 수정

- src/main/java/com/sascom/chickenstock/domain/account/service/AccountService.java
- src/main/java/com/sascom/chickenstock/domain/competition/repository/CompetitionRepository.java
- resolve: #110 
npe 해결
어떤 변경 사항이 있나요?
> [#110] account npe 해결

- src/main/java/com/sascom/chickenstock/domain/auth/service/ChickenstockOauth2MemberService.java
- resolved: #120 
해당 이슈 해결
어떤 변경 사항이 있나요?
> [#120] social login 횟수만큼 ranking list에 같은 유저가 추가되는 이슈 해결

- src/main/java/com/sascom/chickenstock/domain/rival/controller/RivalController.java
- src/main/java/com/sascom/chickenstock/domain/rival/dto/response/CheckRivalResponse.java
- src/main/java/com/sascom/chickenstock/domain/rival/service/RivalService.java
resolve #114 
rival api의 response가 api명세와 일치하지 않아 수정하였습니다.
어떤 변경 사항이 있나요?
> [#114] rival api 수정

- src/main/java/com/sascom/chickenstock/domain/member/dto/response/MemberInfoResponse.java
- src/main/java/com/sascom/chickenstock/domain/member/service/MemberService.java
- src/main/java/com/sascom/chickenstock/domain/ranking/service/RankingService.java
resolve #115 
response에 front에서 필요한 정보(잔고, 등수)가 빠져있어 수정합니다.
어떤 변경 사항이 있나요?
> [#115] 회원 검색 api 수정

- build.gradle
- src/main/java/com/sascom/chickenstock/domain/competition/controller/CompetitionController.java
- src/main/java/com/sascom/chickenstock/domain/fcmtoken/controller/FcmTokenController.java
- src/main/java/com/sascom/chickenstock/domain/fcmtoken/entity/FcmToken.java
- src/main/java/com/sascom/chickenstock/domain/fcmtoken/service/FcmTokenService.java
- src/main/java/com/sascom/chickenstock/domain/member/service/MemberService.java
- src/main/java/com/sascom/chickenstock/global/config/KafkaProducerConfig.java
- src/main/java/com/sascom/chickenstock/global/filter/JwtAuthenticationFilter.java
- src/main/java/com/sascom/chickenstock/global/kafkaproducer/KafkaProducer.java
- src/main/java/com/sascom/chickenstock/global/kafkaproducer/dto/NotificationMessageDto.java
- src/main/java/com/sascom/chickenstock/global/kafkaproducer/properties/ProducerProperties.java
- src/main/resources/application.yml
- resolve: #74
kafka producer 추가
어떤 변경 사항이 있나요?
> [#74] Kafka Producer 추가

- src/main/java/com/sascom/chickenstock/domain/socket/MyStompSessionHandler.java
- src/main/java/com/sascom/chickenstock/domain/trade/service/TradeService.java
resolve #127 
주식 요청 상태를 알림을 보내는 기능을 추가하였습니다.
어떤 변경 사항이 있나요?
> [#127] 메시지 발행 추가

- src/main/java/com/sascom/chickenstock/domain/fcmtoken/service/FcmTokenService.java
> [Fix] - flush()추가

- src/main/java/com/sascom/chickenstock/domain/member/service/MemberService.java
- src/main/java/com/sascom/chickenstock/domain/socket/MyStompSessionHandler.java
- src/main/java/com/sascom/chickenstock/domain/socket/WebSocketClientInitializer.java
resolve #130 
console 출력을 제거하였습니다.
어떤 변경 사항이 있나요?
> [#130] console 출력 삭제

- src/main/java/com/sascom/chickenstock/domain/account/service/AccountService.java
- src/main/java/com/sascom/chickenstock/domain/auth/dto/response/AccountInfoForLogin.java
- src/main/java/com/sascom/chickenstock/domain/auth/dto/response/ResponseLoginMember.java
- src/test/java/com/sascom/chickenstock/domain/auth/AuthControllerTest.java
resolve #131 
[#131] login response 수정
어떤 변경 사항이 있나요?
> [#131] login response 수정
